#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPD.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CPD")]
	public partial class CPDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CPDDataContext() : 
				base(global::CPD.Data.Properties.Settings.Default.CPDConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public CPDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CPDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CPDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CPDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[ResultDoc.Result.IssueCertificate]")]
		public int ResultDoc_Result_IssueCertificate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResultId", DbType="Int")] System.Nullable<int> resultId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateIssued", DbType="DateTime")] System.Nullable<System.DateTime> dateIssued)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), resultId, dateIssued);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
