#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPD.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MIMS3")]
	public partial class MimsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MimsDataContext() : 
				base(global::CPD.Data.Properties.Settings.Default.MIMS3ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MimsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MimsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MimsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MimsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DataContext.AuthoriseCPDIssue]")]
		public ISingleResult<MIMS_DataContext_AuthoriseCPDIssueResult> MIMS_DataContext_AuthoriseCPDIssue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerId", DbType="Int")] System.Nullable<int> customerId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IssueId", DbType="Int")] System.Nullable<int> issueId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerId, issueId);
			return ((ISingleResult<MIMS_DataContext_AuthoriseCPDIssueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[MIMS.DataContext.CustomerInfo]")]
		public ISingleResult<MIMS_DataContext_CustomerInfoResult> MIMS_DataContext_CustomerInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerId", DbType="Int")] System.Nullable<int> customerId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerId);
			return ((ISingleResult<MIMS_DataContext_CustomerInfoResult>)(result.ReturnValue));
		}
	}
	
	public partial class MIMS_DataContext_AuthoriseCPDIssueResult
	{
		
		private int _Column1;
		
		public MIMS_DataContext_AuthoriseCPDIssueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class MIMS_DataContext_CustomerInfoResult
	{
		
		private string _FullName;
		
		private string _EmailAddress;
		
		private string _CouncilNumber;
		
		public MIMS_DataContext_CustomerInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(101) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this._EmailAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CouncilNumber", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string CouncilNumber
		{
			get
			{
				return this._CouncilNumber;
			}
			set
			{
				if ((this._CouncilNumber != value))
				{
					this._CouncilNumber = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
